### ISSUE TITLE
dockerhub repository point to python 3.4

### ISSUE THREAD

**Issue by valgog** [zalando-stups/docker-python#3]
https://hub.docker.com/r/zalando/python/ repository points to the python3.4 version, though the tags include the python 3.5 version as well. Please document the fact, that the repository contains more versions of python, other than 3.4

**Comment by jmcs** [comment]
And it references python 2.7 but the tags for 2.7 are missing.

**Comment by hjacobs** [comment]
OK, changed the Docker Hub description: https://hub.docker.com/r/zalando/python/

@valgog happy now?

**Comment by valgog** [comment]
I am little bit perplexed, that the image for python-2.7 contains some python libraries, like psycopg2... and 3.5 is much more minimalistic. Was there any discussion about it?

I also noticed yesterday, that if python2.7 is not installed at all, some of the packages cannot be installed any longer in the child docker images :(

**Comment by Jan-M** [comment]
Yes, the python2.7 image was build specifically for zmon worker/scheduler and included a reasonable set of libraries already to speed up the build/download process.

**Comment by hjacobs** [comment]
@valgog what packages cannot be installed in child images? Could you be a bit more specific?

**Comment by jmcs** [comment]
Since https://hub.docker.com/r/zalando/python/ no longer exists is this still relevant?
