### ISSUE TITLE
Upgrade to latest stable Python version 3.6

### ISSUE THREAD

**Issue by arphen** [zalando-stups/docker-python#9]
3.6 is now the official latest stable and recommended version of Python. I would like to see this image upgraded. [source](http://blog.python.org/2017/03/python-361-is-now-available.html?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+PythonInsider+%28Python+Insider%29)

**Comment by hjacobs** [comment]
Yes, I agree --- there is a PR #8, but it should IMHO be upgraded in the normal `Dockerfile`.

**Comment by hjacobs** [comment]
Fixed via #8
